### ISSUE TITLE
BashWarning

### ISSUE THREAD

**Issue by JKing-B16** [dom111/bash-todo#1]
I am getting the following warning message in my console after any command:

...TODO.sh: line 166: warning: here-document at line 98 delimited by end-of-file (wanted `PERL')

I have a fix, but I could not figure out how to push it the repo. I've never embedded Perl in a shell script before, but I basically had to take the two following steps:

Change last line from

`"PERL"`
to 
`no strict;
PERL`

Removing the quotes on PERL stopped the Bash Warning, but created a Perl warning. Adding the "no strict;" stopped the Perl warning. However, that only leads to the Perl itself always dieing, but at least it does so quietly. There is probably a better way to get Perl to stop interpreting before the final line.

**Comment by dom111** [comment]
Ahh, thanks for the report! I changed the script to a polyglot and then didn't re-test on my most up-to-date server!

I've fixed this in c86fa80 by exiting before the Perl block (so I don't need a no strict!)

**Comment by JKing-B16** [comment]
Thanks, that fixes it for me too.
